version: 2
updates:
  - package-ecosystem: npm
    assignees:
      - stfsy
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      vuepress:
        patterns:
          - "vuepress*"
          - "@vuepress*"

  - package-ecosystem: github-actions
    assignees:
      - stfsy
    directory: /
    schedule:
      interval: monthly
